@startuml
class Cliente {
    + Cliente()
    + Cliente(direccionFacturacion:string)
    + DireccionFacturacion : string <<get>> <<set>>
    + Compras : List<CompraModelo3D> <<get>> <<set>>
}
ApplicationUser <|-- Cliente
@enduml
