@startuml
class CompraModelo3D {
    + CompraModelo3D()
    + CompraModelo3D(fechaCompra:DateTime, nombreCliente:string, apellidosCliente:string, correoElectronico:string, direccionFacturacion:string, descripcion:string, precioTotal:decimal, metodoPago:MetodoPago, clienteId:string)
    + id : int <<get>> <<set>>
    + FechaCompra : DateTime <<get>> <<set>>
    + NombreCliente : string <<get>> <<set>>
    + ApellidosCliente : string <<get>> <<set>>
    + CorreoElectronico : string <<get>> <<set>>
    + DireccionFacturacion : string <<get>> <<set>>
    + Descripcion : string? <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + MetodoPago : MetodoPago <<get>> <<set>>
    + ClienteId : string <<get>> <<set>>
    + Cliente : Cliente <<get>> <<set>>
    + LineasCompraModelo : List<LineaCompraModelo> <<get>> <<set>>
}
@enduml
