@startuml
!include .\\ApplicationUser.puml
!include .\\Cliente.puml
!include .\\CompraModelo3D.puml
!include .\\FormatoModelo3D.puml
!include .\\LicenciaModelo3D.puml
!include .\\LineaCompraModelo.puml
!include .\\MetodoPago.puml
!include .\\Modelo3D.puml
@enduml
