@startuml
class Modelo3D {
    + Modelo3D()
    + Modelo3D(id:int, nombre:string, categoria:string, formato:FormatoModelo3D, precio:decimal)
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Categoria : string <<get>> <<set>>
    + Formato : FormatoModelo3D <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + LineasCompraModelo : List<LineaCompraModelo> <<get>> <<set>>
    + Licencias : List<LicenciaModelo3D> <<get>> <<set>>
}
@enduml
